# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-12-04 09:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20171204_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogs',
            old_name='author',
            new_name='owner',
        ),
    ]
